# Generated by Django 3.0.4 on 2020-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
    ]
